version: 2

updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    ignore:
      - dependency-name: obsidian
    reviewers:
      - leonhma
    commit-message:
      include: scope
      prefix: chore
