version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "obsidian"
    # Disable version updates
    open-pull-requests-limit: 0
