version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    versioning-strategy: increase-if-necessary
    ignore:
      - dependency-name: obsidian
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
