name: CI

on: [push]

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ github.ref }}"

  build:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/')
    steps:
      - uses: actions/checkout@v2
        
      - name: install dependencies
        run: yarn install

      - name: build
        run: yarn build

