name: release

on:
  release:
    types: [ published ] 
    
jobs:
  
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.1.1
      with:
        node-version: 14

    - name: Download repo
      run: |
        git clone ${{ github.repositoryUrl }} .
        cd ${{ github.repository.name }}

    - name: Install packages
      run: yarn install

    - name: Run version-bump
      run: node version-bump.mjs

    - name: Push changes to github
      run: |
        git add -A
        git config --global user.name "${{ github.event.sender.login }}"
        git commit -m '[chore] index minAppVersion for release of ${{ github.ref }}'
        git push origin ${{ github.ref }}

    - name: Build
      run: yarn build

    - name: Upload assets to a Release
      uses: AButler/upload-release-assets@v2.0
      with:
        repo-token: ${{ github.token }}
        files: "main.js;manifest.json;styles.js"
